[build]
  functions = "netlify/functions"
  command = "cd domains && npm install && npm run build"
  publish = "."

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/domains/client/*"
  to = "/domains/index.html"
  status = 200
